calendar_events/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from gcevent.views import *

urlpatterns = [
    # path('', index, name='index'),
    path('', index2, name='index2'),
    path('get-token', getAuthToken, name='get.auth.token'),
    path('oauth2callback', oauthCallback, name='oauth.callback'),
    path('oauth-response/<str:msg>', oauthResponse, name='oauth.response'),
    path('user-list', userList, name='user.list'),
    path('celery-log', celeryLog, name='celery.log'),
    path('user-list/fetch-events/<str:uid>', fetchEvents, name='user.fetch.events'),
    path('user-list/fetch-contacts/<str:uid>', fetchContacts, name='user.fetch.contacts'),
    path('user-list/view-events/<str:uid>', viewEvents, name='user.view.events'),
    path('user-list/delete/<str:uid>', deleteUser, name='user.delete'),
    path('accounts/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gcevent/models.py
from django.db import models


# Create your models here.
class UserCredentials(models.Model):
    uid = models.CharField(max_length=200, unique=True)
    state = models.TextField()
    code = models.TextField()
    scope = models.TextField()
    credentials = models.JSONField()
    profile = models.JSONField()
    celery_run = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.profile['name']


class Events(models.Model):
    user = models.ManyToManyField(UserCredentials)
    ev_id = models.CharField(max_length=200, unique=True)
    summary = models.TextField(null=True)
    status = models.CharField(max_length=200)
    link = models.URLField()
    event_json = models.JSONField()
    created_at = models.DateTimeField()

    def __str__(self):
        return self.summary


class CeleryLog(models.Model):
    event_fetched = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

gcevent/views.py
from __future__ import print_function

import json
import os.path

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponseRedirect, reverse
from google.auth.transport.requests import Request as RequestG
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from .models import *

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/calendar.readonly', 'https://www.googleapis.com/auth/contacts.readonly',
          'https://www.googleapis.com/auth/userinfo.email',
          'https://www.googleapis.com/auth/userinfo.profile', 'openid']

cred_path = os.path.join(settings.BASE_DIR, 'gcevent/client_secret.json')


def seed():
    if not User.objects.filter(username='gcevent').exists():
        instance = User.objects.create(
            first_name='GC',
            last_name='Event',
            email='gcevent@gcevent.com',
            username='gcevent',
            is_superuser=True,
            is_staff=True
        )
        instance.set_password('gcevent')
        instance.save()


def index(request):
    seed()
    if settings.DEBUG:
        os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
    return render(request, 'gcevent/index.html')


def index2(request):
    seed()
    if settings.DEBUG:
        os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
    return render(request, 'gcevent/index2.html')


def getAuthToken(request):
    # Use the client_secret.json file to identify the application requesting
    # authorization. The client ID (from that file) and access scopes are required.
    flow = Flow.from_client_secrets_file(cred_path, SCOPES)

    # Indicate where the API server will redirect the user after the user completes
    # the authorization flow. The redirect URI is required. The value must exactly
    # match one of the authorized redirect URIs for the OAuth 2.0 client, which you
    # configured in the API Console. If this value doesn't match an authorized URI,
    # you will get a 'redirect_uri_mismatch' error.
    redirect_uri = request.build_absolute_uri(reverse('oauth.callback'))
    if "http:" in redirect_uri:
        redirect_uri = "https:" + redirect_uri[5:]
    flow.redirect_uri = redirect_uri

    # Generate URL for request to Google's OAuth 2.0 server.
    # Use kwargs to set optional request parameters.
    authorization_url, state = flow.authorization_url(
        # Enable offline access so that you can refresh an access token without
        # re-prompting the user for permission. Recommended for web server apps.
        access_type='offline',
        # Enable incremental authorization. Recommended as a best practice.
        include_granted_scopes='true')
    return HttpResponseRedirect(authorization_url)


def oauthCallback(request):
    authorization_response = request.build_absolute_uri()
    if "http:" in authorization_response:
        authorization_response = "https:" + authorization_response[5:]
    # Use the client_secret.json file to identify the application requesting
    # authorization. The client ID (from that file) and access scopes are required.
    flow = Flow.from_client_secrets_file(cred_path, SCOPES, state=request.GET['state'])
    redirect_uri = request.build_absolute_uri(reverse('oauth.callback'))
    if "http:" in redirect_uri:
        redirect_uri = "https:" + redirect_uri[5:]
    flow.redirect_uri = redirect_uri

    flow.fetch_token(authorization_response=authorization_response)

    # Credential object
    credentials = flow.credentials

    user_profile = getUserProfileInfo(credentials.token)
    # credentials = {
    #     'token': credentials.token,
    #     'refresh_token': credentials.refresh_token,
    #     'token_uri': credentials.token_uri,
    #     'client_id': credentials.client_id,
    #     'client_secret': credentials.client_secret,
    #     'scopes': credentials.scopes
    # }

    if not UserCredentials.objects.filter(uid=user_profile['id']).exists():
        UserCredentials.objects.create(
            uid=user_profile['id'],
            state=request.GET['state'],
            code=request.GET['code'],
            scope=request.GET['scope'],
            credentials=json.loads(credentials.to_json()),
            profile=user_profile
        )
        response = {
            'msg': 'You have successfully granted access to view your calendar events.'
        }
    else:
        response = {
            'msg': 'You have already granted access to view your calendar events.'
        }

    return HttpResponseRedirect(reverse('oauth.response', kwargs={'msg': response.get('msg')}))


def getUserProfileInfo(token):
    url = f"https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token={token}"

    payload = {}
    headers = {}

    response = requests.request("GET", url, headers=headers, data=payload)

    return json.loads(response.text)


def oauthResponse(request, msg):
    context = {
        'msg': msg
    }
    return render(request, 'gcevent/success.html', context)


@login_required
def celeryLog(request):
    celery_log = CeleryLog.objects.all().order_by('-created_at')
    context = {
        'celery_log': celery_log
    }
    return render(request, 'gcevent/celery-log.html', context)


@login_required
def userList(request):
    user_list = UserCredentials.objects.all().order_by('created_at')
    context = {
        'user_list': user_list
    }
    return render(request, 'gcevent/user-list.html', context)


@login_required
def fetchEvents(request, uid):
    user = UserCredentials.objects.get(uid=uid)
    credentials = user.credentials
    # import six
    # print(six.iterkeys(credentials))

    # token_file = os.path.join(settings.BASE_DIR, f'gcevent/tokens/{uid}.json')
    # token = open(token_file, "w")
    # token.write("Woops! I have deleted the content!")
    # token.close()

    # creds = Credentials.from_authorized_user_file(token_file, SCOPES)
    creds = Credentials.from_authorized_user_info(credentials, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(RequestG())
        else:
            messages.error(request, 'Invalid/Expired credentials! Please authorize again.')
            return HttpResponseRedirect(reverse('user.list'))

    try:
        service = build('calendar', 'v3', credentials=creds)

        # Call the Calendar API
        events_result = service.events().list(calendarId='primary').execute()
        events = events_result.get('items', [])

        for event in events:
            try:
                if Events.objects.filter(ev_id=event['id']).exists():
                    ev_instance = Events.objects.get(ev_id=event['id'])
                    ev_instance.summary = event['summary']
                    ev_instance.status = event['status']
                    ev_instance.link = event['htmlLink']
                    ev_instance.event_json = event
                    ev_instance.created_at = event['created']
                    ev_instance.save()
                else:
                    ev_instance = Events.objects.create(
                        ev_id=event['id'],
                        summary=event['summary'],
                        status=event['status'],
                        link=event['htmlLink'],
                        event_json=event,
                        created_at=event['created']
                    )
                    ev_instance.user.add(user)
            except Exception:
                pass
        messages.success(request, 'Events fetched successfully!')
    except HttpError as error:
        messages.error(request, 'An error occurred: %s' % error)

    return HttpResponseRedirect(reverse('user.list'))


@login_required
def fetchContacts(request, uid):
    user = UserCredentials.objects.get(uid=uid)
    credentials = user.credentials
    # import six
    # print(six.iterkeys(credentials))

    # token_file = os.path.join(settings.BASE_DIR, f'gcevent/tokens/{uid}.json')
    # token = open(token_file, "w")
    # token.write("Woops! I have deleted the content!")
    # token.close()

    # creds = Credentials.from_authorized_user_file(token_file, SCOPES)
    creds = Credentials.from_authorized_user_info(credentials, SCOPES)

    contacts = []

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(RequestG())
        else:
            messages.error(request, 'Invalid/Expired credentials! Please authorize again.')
            return HttpResponseRedirect(reverse('user.list'))

    try:
        service = build('people', 'v1', credentials=creds)

        # Call the People API
        results = service.people().connections().list(
            resourceName='people/me',
            personFields='names,photos,emailAddresses').execute()
        connections = results.get('connections', [])

        for person in connections:
            names = person.get('names', [])
            emails = person.get('emailAddresses', [])
            photos = person.get('photos', [])
            name = ''
            email = ''
            photo = ''
            if names:
                name = names[0].get('displayName')
            if emails:
                email = emails[0].get('value')
            if photos:
                photo = photos[0].get('url')
            contacts.append({
                'name': name,
                'email': email,
                'photo': photo
            })

        context = {
            'contacts': contacts
        }

        return render(request, 'gcevent/contact-list.html', context)
        # messages.success(request, 'Contacts fetched successfully!')

gcevent/templates/gcevent/app.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>

    <title>GC Event</title>

    <!-- MDB icon -->
    <link rel="icon" href="https://sidekickai.com/wp-content/uploads/2021/11/g-cal.png" type="image/x-icon"/>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.css" rel="stylesheet"/>
    {% block css %}{% endblock %}
</head>
<body>
{% block content %}{% endblock %}
<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>

gcevent/templates/gcevent/celery-log.html
{% extends 'gcevent/app.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.css"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row p-5">
            <div class="col-12 text-center">
                <img class="p-3" src="https://sidekickai.com/wp-content/uploads/2021/11/g-cal.png"
                     width="100px">
                <h3 class="mb-0">GC Event - Celery Log</h3>
                <small>A way to collect all the events from a user's calendar.</small>
                <br>
                <a href="{% url 'index' %}">
                    <button type="button" class="btn btn-primary mt-3">Go to Home</button>
                </a>
                <a href="/accounts">
                    <button class="btn btn-dark">Go to Django Admin</button>
                </a>
            </div>
            <div class="col-12 my-3">
                <hr>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-primary" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <table class="table table-striped" id="datatable">
                    <thead>
                    <tr>
                        <th class="text-center">ID</th>
                        <th class="text-center">Event Fetched</th>
                        <th class="text-center">Timestamp (UTC)</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for log in celery_log %}
                        <tr>
                            <td class="text-center">
                                {{ forloop.counter }}
                            </td>
                            <td class="text-center">
                                {{ log.event_fetched|floatformat:0 }}
                            </td>
                            <td class="text-center">{{ log.created_at }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.js"></script>
    <script>
        $("#datatable").DataTable();
    </script>
{% endblock %}

gcevent/templates/gcevent/contact-list.html
{% extends 'gcevent/app.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.css"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row p-5">
            <div class="col-12 text-center">
                <img class="p-3" src="https://sidekickai.com/wp-content/uploads/2021/11/g-cal.png"
                     width="100px">
                <h3 class="mb-0">GC Event - Contact List</h3>
                <small>A way to collect all the contact from a user.</small>
                <br>
                <a href="{% url 'index' %}">
                    <button type="button" class="btn btn-primary mt-3">Go to Home</button>
                </a>
                <a href="/accounts">
                    <button class="btn btn-dark">Go to Django Admin</button>
                </a>
            </div>
            <div class="col-12 my-3">
                <hr>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-primary" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <table class="table table-striped" id="datatable">
                    <thead>
                    <tr>
                        <th class="text-center">ID</th>
                        <th class="text-center">Photo</th>
                        <th>Name</th>
                        <th class="text-center">Email</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for contact in contacts %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}</td>
                            <td class="text-center">
                                <img src="{{ contact.photo }}" width="40"/>
                            </td>
                            <td>{{ contact.name }}</td>
                            <td class="text-center">{{ contact.email }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.js"></script>
    <script>
        $("#datatable").DataTable();
    </script>
{% endblock %}

gcevent/templates/gcevent/event-list.html
{% extends 'gcevent/app.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.css"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row p-5">
            <div class="col-12 text-center">
                <img class="p-3" src="https://sidekickai.com/wp-content/uploads/2021/11/g-cal.png"
                     width="100px">
                <h3 class="mb-0">GC Event - Event List of {{ user_info.profile.email }}</h3>
                <small>A way to collect all the events from a user's calendar.</small>
                <br>
                <a href="{% url 'index' %}">
                    <button type="button" class="btn btn-primary mt-3">Go to Home</button>
                </a>
                <a href="{% url 'user.list' %}">
                    <button type="button" class="btn btn-secondary mt-3">Go to Users</button>
                </a>
                <a href="/accounts">
                    <button class="btn btn-dark">Go to Django Admin</button>
                </a>
            </div>
            <div class="col-12 my-3">
                <hr>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-primary" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <table class="table table-striped" id="datatable">
                    <thead>
                    <tr>
                        <th class="text-center">Event ID</th>
                        <th class="text-center">Information</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in event_list %}
                        <tr>
                            <td class="text-center">
                                <a href="{{ event.link }}" target="_blank">
                                    {{ event.summary }}
                                </a>
                                <br>
                                {{ event.ev_id }}
                            </td>
                            <td>
                                <b>kind</b>: {{ event.event_json.kind }}
                                <br>
                                <b>etag</b>: {{ event.event_json.etag }}
                                <br>
                                <b>id</b>: {{ event.event_json.id }}
                                <br>
                                <b>status</b>: {{ event.event_json.status }}
                                <br>
                                <b>htmlLink</b>: <a href="{{ event.event_json.htmlLink }}">Click Here</a>
                                <br>
                                <b>created</b>: {{ event.event_json.created }}
                                <br>
                                <b>updated</b>: {{ event.event_json.updated }}
                                <br>
                                <b>summary</b>: {{ event.event_json.summary }}
                                <br>
                                <b>creator_email</b>: {{ event.event_json.creator.email }}
                                <br>
                                <b>creator_self</b>: {{ event.event_json.creator.self }}
                                <br>
                                <b>organizer_email</b>: {{ event.event_json.organizer.email }}
                                <br>
                                <b>organizer_self</b>: {{ event.event_json.organizer.self }}
                                <br>
                                <b>start_dateTime</b>: {{ event.event_json.start.dateTime }}
                                <br>
                                <b>start_timeZone</b>: {{ event.event_json.start.timeZone }}
                                <br>
                                <b>end_dateTime</b>: {{ event.event_json.end.dateTime }}
                                <br>
                                <b>end_timeZone</b>: {{ event.event_json.end.timeZone }}
                                <br>
                                <b>iCalUID</b>: {{ event.event_json.iCalUID }}
                                <br>
                                <b>sequence</b>: {{ event.event_json.sequence }}
                                <br>
                                <b>reminders</b>: {{ event.event_json.reminders.useDefault }}
                                <br>
                                <b>eventType</b>: {{ event.event_json.eventType }}
                                {#                                {{ event.event_json }}#}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.js"></script>
    <script>
        $("#datatable").DataTable();
    </script>
{% endblock %}

gcevent/templates/gcevent/index.html
{% extends 'gcevent/app.html' %}

{% block content %}
    <div class="container">
        <div class="row p-5">
            <div class="col-12 text-center">
                <img class="p-3" src="https://sidekickai.com/wp-content/uploads/2021/11/g-cal.png"
                     width="100px">
                <h3 class="mb-0">GC Event</h3>
                <small>A way to collect all the events from a user's calendar.</small>
            </div>
            <div class="col-12 text-center my-3">
                <a href="{% url 'get.auth.token' %}">
                    <button id="authorize_button" class="btn btn-primary" onclick="this.disabled=true;">
                        Connect Google
                    </button>
                </a>
            </div>
            <div class="col-12 text-center mt-5">
                <h3>Control Panel</h3>
                <p>
                    <i>
                        <b>Default Username:</b> gcevent
                        <br>
                        <b>Default Password:</b> gcevent
                    </i>
                </p>
                <a href="/accounts">
                    <button class="btn btn-dark">Go to Django Admin</button>
                </a>
                <a href="{% url 'user.list' %}">
                    <button type="button" class="btn btn-success">View User List</button>
                </a>
                <a href="{% url 'celery.log' %}">
                    <button type="button" class="btn btn-info">View Celery Log</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

gcevent/templates/gcevent/user-list.html
{% extends 'gcevent/app.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.css"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row p-5">
            <div class="col-12 text-center">
                <img class="p-3" src="https://sidekickai.com/wp-content/uploads/2021/11/g-cal.png"
                     width="100px">
                <h3 class="mb-0">GC Event - User List</h3>
                <small>A way to collect all the events from a user's calendar.</small>
                <br>
                <a href="{% url 'index' %}">
                    <button type="button" class="btn btn-primary mt-3">Go to Home</button>
                </a>
                <a href="/accounts">
                    <button class="btn btn-dark">Go to Django Admin</button>
                </a>
            </div>
            <div class="col-12 my-3">
                <hr>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-primary" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <table class="table table-striped" id="datatable">
                    <thead>
                    <tr>
                        <th class="text-center">ID</th>
                        <th class="text-center">Photo</th>
                        <th>Name & Email</th>
                        <th class="text-center">Total Events</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in user_list %}
                        <tr>
                            <td class="text-center">
                                {{ user.uid }}
                                {% if user.celery_run is not None %}
                                    <br>
                                    <small>Updated at {{ user.celery_run|date:"d M Y h:m:s A" }}</small>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <img src="{{ user.profile.picture }}" width="40"/>
                            </td>
                            <td>
                                {{ user.profile.name }}
                                <br>
                                <small>{{ user.profile.email }}</small>
                            </td>
                            <td class="text-center">{{ user.events_set.all|length }}</td>
                            <td class="text-center">
                                <a href="{% url 'user.fetch.events' user.uid %}">
                                    <button type="button" class="btn btn-outline-primary btn-sm">Fetch Events</button>
                                </a>
                                <a href="{% url 'user.view.events' user.uid %}">
                                    <button type="button" class="btn btn-outline-success btn-sm">View Events</button>
                                </a>
                                <a href="{% url 'user.delete' user.uid %}" onclick="return confirm('Are you sure?')">
                                    <button type="button" class="btn btn-outline-danger btn-sm">Delete</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.js"></script>
    <script>
        $("#datatable").DataTable();
    </script>
{% endblock %}